# 导航菜单
menu:
  首页: / || fas fa-home
  归档: /archives/ || fas fa-archive
  标签: /tags/ || fas fa-tags
  分类: /categories/ || fas fa-folder-open
# 代码相关
highlight_theme: mac
# 搜索
local_search:
  enable: true
  preload: true
# Favicon（网站图标）
favicon: /favicon.ico
# 头像
avatar:
  img: /img/avatar.png
# 顶部图
disable_top_img: true
# 文章封面
cover:
  default_cover:
    - /img/cover.jpg
# 404
error_404:
  enable: true
  subtitle: '页面没有找到'
  background: /img/404.png
# 字数统计
wordcount:
  enable: true
# 分享
sharejs:
  sites: wechat,weibo,qq
# 评论
comments:
  use: waline
waline:
  serverURL: https://waline.我爱学习.tk
  bg: /img/comment_bg.png
  pageview: true
# 页脚
footer:
  owner:
    since: 2022
# 加载动画
preloader:
  enable: true
# 侧边栏
aside:
  card_author:
    button:
      enable: false
  card_announcement:
    enable: false
# 网页运行时间
runtimeshow:
  enable: true
  publish_date: 10/15/2022 00:00:00
# 简繁转换
translate:
  enable: true
# 弹窗
snackbar:
  enable: true
  position: top-center
# 设置网站背景
background: '#f7f9fe'
# 51la统计
# 51.la Analytics
# https://v6.51.la/
woyaola_analytics: JqgzBIvsnmUv6km4
woyaola_perf: Jqh0YIcvqa28nvHh
# 插入代码到头部 </head> 之前 和 底部 </body> 之前
inject:
  head:
    - <link rel="stylesheet" href="/css/footer.css">
  bottom:
    # - <script src="js/blog.js"></script>
CDN:
  third_party_provider: local